steps:
  # Build the API Server image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/catalog-search/api:latest'
      - '-f'
      - 'docker/api/Dockerfile'
      - '.'
    id: 'build-api'

  # Build the Frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/catalog-search/frontend:latest'
      - '-f'
      - 'docker/frontend/Dockerfile'
      - '.'
    id: 'build-frontend'

  # Build the custom OpenSearch image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/catalog-search/opensearch:latest'
      - '-f'
      - 'docker/opensearch/Dockerfile'
      - '.'
    id: 'build-opensearch'

# Push all the images to Artifact Registry
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/catalog-search/api:latest'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/catalog-search/frontend:latest'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/catalog-search/opensearch:latest'

options:
  logging: CLOUD_LOGGING_ONLY
