# config.yaml
crawler:
  base_pdf_path: "{HOME}/cataloguesearch/pdf"
  base_text_path: "{HOME}/cataloguesearch/text"
  tmp_images_path: "{HOME}/cataloguesearch/tmp_images"
  sqlite_db_path: "{HOME}/cataloguesearch/db/cataloguesearch.db"

index:
  opensearch_config: "{BASE_DIR}/configs/opensearch-config.yaml"
  chunking_algos:
    default:
      chunk_size: 500
      chunk_overlap: 50
    dynamic:
      similarity_threshold: 0.5
  chunk_strategy: "dynamic"

opensearch:
  host: localhost
  port: 9200
  username: admin
  password: Admin@Password123!
  index_name: document_chunks_prod

embedding_model:
  name: ai4bharat/indic-bert

llm_model:
  name: gemini-2.0-flash
  api_key: "{LLM_API_KEY}" # This will be loaded as an environment variable
