# config.yaml
crawler:
  base_pdf_path: {HOME}/cataloguesearch/pdf
  base_text_path: {HOME}/cataloguesearch/text
  tmp_images_path: {HOME}/cataloguesearch/tmp_images
  sqllite_db_path: {HOME}/cataloguesearch/db/cataloguesearch.db

index:
  chunk_size: 500
  chunk_overlap: 50

opensearch:
  host: localhost
  port: 9200
  username: admin
  password: your_secure_password # IMPORTANT: Change this!
  index_name: document_chunks_prod

embedding_model:
  name: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

llm_model:
  name: gemini-2.0-flash
  api_key: {LLM_API_KEY} # This will be loaded as an environment variable