# config.yaml
crawler:
  base_pdf_path: "{HOME}/github/rajatjain/cataloguesearch-configs"
  base_text_path: "{HOME}/cataloguesearch/text"
  base_ocr_path: "{HOME}/cataloguesearch/ocr"
  sqlite_db_path: "{HOME}/cataloguesearch/db/cataloguesearch.db"

index:
  opensearch_config: "{BASE_DIR}/configs/opensearch-config.yaml"
  chunking_algos:
    default:
      chunk_size: 500
      chunk_overlap: 50
    dynamic:
      similarity_threshold: 0.5
  chunk_strategy: "paragraph"

search:
  filtered_metadata_fields: ["Year", "Granth", "Anuyog"]

opensearch:
  host: "{OPENSEARCH_HOST}"
  port: "{OPENSEARCH_PORT}"
  index_name: cataloguesearch_prod
  metadata_index_name: cataloguesearch_prod_metadata
  granth_index_name: cataloguesearch_prod_granth

vector_embeddings:
  embedding_model: BAAI/bge-m3
  reranking_model: BAAI/bge-reranker-base
  # Path to the optimized ONNX model directory inside the container.
  # If this path exists, the application will use the faster ONNX model.
  reranker_onnx_path: "{BASE_DIR}/models/bge-reranker-base-onnx"
  # Supported types: base, fp16, quantized_8bit
  embedding_model_type: fp16
