search_index:
  settings:
    "index.knn": true
    number_of_shards: 1
    number_of_replicas: 0
    analysis:
      char_filter:
        # Normalize everything to anusvara form
        hindi_nasal_normalizer:
          type: mapping
          mappings:
            # N-based conjuncts (न)
            - "न्त => ंत"
            - "न्थ => ंथ"
            - "न्द => ंद"
            - "न्ध => ंध"
            - "न्न => ंन"
            - "न्स => ंस"
            - "न्श => ंश"
            - "न्ह => ंह"
            - "न्य => ंय"
            - "न्व => ंव"
            - "न्ल => ंल"
            - "न्र => ंर"
            - "न्च => ंच"
            - "न्छ => ंछ"
            - "न्ज => ंज"
            - "न्झ => ंझ"
            - "न्क => ंक"
            - "न्ख => ंख"
            - "न्ग => ंग"
            - "न्घ => ंघ"
            # NN-based conjuncts (ण)
            - "ण्ट => ंट"
            - "ण्ठ => ंठ"
            - "ण्ड => ंड"
            - "ण्ढ => ंढ"
            - "ण्ण => ंण"
            # M-based conjuncts (म)
            - "म्प => ंप"
            - "म्फ => ंफ"
            - "म्ब => ंब"
            - "म्भ => ंभ"
            - "म्म => ंम"
            # Velar Nasal (ङ्) conjuncts
            - "ङ्क => ंक"
            - "ङ्ख => ंख"
            - "ङ्ग => ंग"
            - "ङ्घ => ंघ"
            # Palatal Nasal (ञ्) conjuncts
            - "ञ्च => ंच"
            - "ञ्छ => ंछ"
            - "ञ्ज => ंज"
            - "ञ्झ => ंझ"

        gujarati_nasal_normalizer:
          type: mapping
          mappings:
            # N-based conjuncts (ન)
            - "ન્ત => ંત"
            - "ન્થ => ંથ"
            - "ન્દ => ંદ"
            - "ન્ધ => ંધ"
            - "ન્ન =>ંન"
            - "ન્સ => ંસ"
            - "ન્શ => ંશ"
            - "ન્ચ => ંચ"
            - "न्छ => ंछ"
            - "ન્જ => ંજ"
            - "ન્ઝ => ંઝ"
            - "ન્ક => ંક"
            - "ન્ખ => ંખ"
            - "ન્ગ => ંગ"
            - "ન્ઘ => ંઘ"
            # M-based conjuncts (મ)
            - "મ્પ => ંપ"
            - "મ્ફ => ंફ"
            - "મ્બ => ંબ"
            - "મ્ભ => ંભ"
            - "મ્મ => ંમ"
            # NN-based conjuncts (ણ)
            - "ણ્ટ => ંટ"
            - "ણ્ઠ => ંઠ"
            - "ણ્ડ => ંડ"
            - "ણ્ઢ => ંઢ"
            - "ણ્ણ =>ંણ"

      analyzer:
        hindi_analyzer:
          tokenizer: icu_tokenizer
          char_filter:
            - hindi_nasal_normalizer
          filter:
            - lowercase
            - indic_normalizer
            - hindi_stop
        gujarati_analyzer:
          tokenizer: icu_tokenizer
          char_filter:
            - gujarati_nasal_normalizer
          filter:
            - lowercase
            - indic_normalizer
            - gujarati_stop
      filter:
        hindi_stop:
          type: stop
          stopwords: "_hindi_"
        gujarati_stop:
          type: "stop"
          stopwords: "_gujarati_"
        indic_normalizer:
          type: icu_normalizer
          name: nfkc_cf

  mappings:
    properties:
      document_id:
        type: keyword
      original_filename:
        type: keyword
      page_number:
        type: integer
      chunk_id:
        type: keyword
      text_content_hindi:
        type: text
        analyzer: hindi_analyzer
        search_analyzer: hindi_analyzer
      text_content_gujarati:
        type: text
        analyzer: gujarati_analyzer
        search_analyzer: gujarati_analyzer
      metadata:
        type: object
      bookmarks:
        type: text
      timestamp_indexed:
        type: date
      paragraph_id:
        type: keyword
      vector_embedding:
        type: knn_vector
        dimension: 1024
        method:
          name: hnsw
          space_type: cosinesimil
          engine: faiss
          parameters:
            ef_construction: 256
            m: 48

metadata_index:
  settings:
    number_of_shards: 1
    number_of_replicas: 0
  mappings:
    properties:
      values:
        type: keyword
