# Settings for the OpenSearch index
settings:
  # The knn settings must be prefixed with 'index.' and be at the top level
  "index.knn": true

  # Standard index settings do not have a prefix
  number_of_shards: 1
  number_of_replicas: 0
  analysis:
    analyzer:
      hindi_analyzer:
        tokenizer: standard
        filter:
          - lowercase
          - hindi_stop
          - indic_normalizer
      gujarati_analyzer:
        tokenizer: standard
        filter:
          - lowercase
          - gujarati_stop
          - indic_normalizer
    filter:
      hindi_stop:
        type: stop
        stopwords: "_hindi_"
      gujarati_stop:
        type: "stop"
        stopwords: "_gujarati_"
      indic_normalizer:
        type: icu_normalizer
        name: nfkc_cf

# Mappings define the schema for documents in the index
mappings:
  properties:
    document_id:
      type: keyword
    original_filename:
      type: keyword
    page_number:
      type: integer
    chunk_id:
      type: keyword
    text_content:
      type: text
      analyzer: standard
    text_content_hindi:
      type: text
      analyzer: hindi_analyzer
    text_content_gujarati:
      type: text
      analyzer: gujarati_analyzer
    metadata:
      type: object
    bookmarks:
      type: text
    timestamp_indexed:
      type: date
    paragraph_id:
      type: keyword
    chunk_in_para_index:
      type: integer
    vector_embedding:
      type: knn_vector
      # The dimension for ai4bharat/sentence-embedding-indic-bert is 768.
      dimension: 768
      method:
        name: hnsw
        # The embeddings will be normalized for faster and more accurate similarity search.
        # Hence use cosinesimil as the distance metric.
        space_type: cosinesimil
        engine: faiss
        parameters:
          # Number of neighbors to connect to during graph construction.
          # Higher values lead to better recall but slower indexing.
          ef_construction: 256
          # The number of bidirectional links for each new element.
          m: 48