search_index:
  settings:
    "index.knn": true
    number_of_shards: 1
    number_of_replicas: 0
    analysis:
      char_filter:
        # Normalize everything to anusvara form
        hindi_nasal_normalizer:
          type: mapping
          mappings:
            # Convert all halant forms to anusvara
            - "न्त => ंत"
            - "न्थ => ंथ"
            - "न्द => ंद"
            - "न्ध => ंध"
            - "न्न => ंन"
            - "न्स => ंस"
            - "न्श => ंश"
            - "न्ह => ंह"
            - "न्य => ंय"
            - "न्व => ंव"
            - "न्ल => ंल"
            - "न्र => ंर"
            - "न्च => ंच"
            - "न्छ => ंछ"
            - "न्ज => ंज"
            - "न्झ => ंझ"
            - "न्क => ंक"
            - "न्ख => ंख"
            - "न्ग => ंग"
            - "न्घ => ंघ"
            - "ण्ट => ंट"
            - "ण्ठ => ंठ"
            - "ण्ड => ंड"
            - "ण्ढ => ंढ"
            - "ण्ण => ंण"
            - "म्प => ंप"
            - "म्फ => ंफ"
            - "म्ब => ंब"
            - "म्भ => ंभ"
            - "म्म => ंम"
      analyzer:
        hindi_analyzer:
          # UPDATED: Changed tokenizer from 'standard' to 'icu_tokenizer'
          tokenizer: icu_tokenizer
          char_filter:
            - hindi_nasal_normalizer
          filter:
            - lowercase
            - indic_normalizer
            - hindi_stop
        gujarati_analyzer:
          # It's good practice to use icu_tokenizer for Gujarati as well
          tokenizer: icu_tokenizer
          filter:
            - lowercase
            - indic_normalizer
            - gujarati_stop
      filter:
        hindi_stop:
          type: stop
          stopwords: "_hindi_"
        gujarati_stop:
          type: "stop"
          stopwords: "_gujarati_"
        indic_normalizer:
          type: icu_normalizer
          name: nfkc_cf

  # Mappings - IMPORTANT: Ensure search_analyzer is also set!
  mappings:
    properties:
      document_id:
        type: keyword
      original_filename:
        type: keyword
      page_number:
        type: integer
      chunk_id:
        type: keyword
      text_content:
        type: text
        analyzer: standard
      text_content_hindi:
        type: text
        analyzer: hindi_analyzer
        search_analyzer: hindi_analyzer  # Explicitly set search analyzer
      text_content_gujarati:
        type: text
        analyzer: gujarati_analyzer
        search_analyzer: gujarati_analyzer  # Explicitly set search analyzer
      metadata:
        type: object
      bookmarks:
        type: text
      timestamp_indexed:
        type: date
      paragraph_id:
        type: keyword
      vector_embedding:
        type: knn_vector
        dimension: 1024
        method:
          name: hnsw
          space_type: cosinesimil
          engine: faiss
          parameters:
            ef_construction: 256
            m: 48

# New index definition for optimized metadata lookups
metadata_index:
  settings:
    number_of_shards: 1
    number_of_replicas: 0
  mappings:
    properties:
      values: # This field will hold an array of unique string values for a given metadata key
        type: keyword
